services:
  open_transaction_notifier:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.toml:/app/config.toml
    environment:
      - NOTIFICATION_METHOD=discord_webhook
      - NOTIFICATION_INFO=your_discord_webhook_url